"""Generate the dictionary chapters of the founding text from the (frozen) lexicon and the book's coinages.

  (default)  the Book of Roots, conlang/book/08_roots.tl: every root
  --first    the First Words, conlang/book/02b_first_words.tl: the relators, the most frequent words and the
             words this book coined, taught right after the three rules

Every entry is itself a Talema tree. The root heads, first, its word class (a Talema word: `nomun` noun,
`verab` verb …), then its mother words as literals: `ferasu nomuna sentence-a satz-a frase-a` is the root
feras with four children. Entries follow Talema's own alphabetical order, p t k b d g m n l r s f v h, then
a e i o u, grouped by first letter. The chapters' opening sentences, which explain all this in Talema, are
templates in this file.

  .venv/bin/python scripts/conlang/roots_book.py --out conlang/book/08_roots.tl
  .venv/bin/python scripts/conlang/roots_book.py --first --out conlang/book/02b_first_words.tl
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts" / "conlang"))
from conlang import numeral  # noqa: E402

ORDER = {ch: i for i, ch in enumerate("ptkbdgmnlrsfvhaeiou")}
# word class → the Talema word that names it (coined in conlang/book/coin.tsv, or already in the lexicon)
CLASS_WORD = {"NOUN": "nomun", "VERB": "verab", "ADJ": "detiv", "ADV": "derob", "ADP": "pepos", "CCONJ": "dunon",
              "SCONJ": "dunon", "DET": "tik", "PRON": "ronon", "NUM": "numer", "PART": "patik", "INTJ": "teron",
              "ROLE": "patik"}
RELATOR_CLASSES = {"ADP", "CCONJ", "SCONJ", "ROLE"}
ROLE_WORDS = {"<subject>": ["subject", "Subjekt", "sujeto"], "<object>": ["object", "Objekt", "objeto"],
              "<to-whom>": ["recipient", "Empfänger", "destinatario"]}
# rough words (web-text frequency brought them in): kept, since roots are never reassigned, but fenced off in their
# own section at the end of the book of roots rather than listed beside core words
ROUGH = {"bitch", "bullshit", "dick", "shit", "fuck", "fucking", "ass", "damn"}

ROOTS_HEADER = '''# Chapter 8 · The book of roots. Generated by scripts/conlang/roots_book.py; do not edit by hand.
## (book (of root) the)

(be (book (of root) the) (SUBJ this))                                        # This is the book of roots.
(stand first/ADV (in (line every)) (SUBJ (root a)))                          # In every line a root stands first,
(stand (with hyphen) alone (SUBJ it))                                        # alone, with a ginon:
@verse
("sahen" verb "count" "zählen")
@prose
(be "sahen" (SUBJ (root the)))                                               # The root is sahen.
(count/VERB (OBJ (child its)) (SUBJ (ending (after (hyphen the)))))          # The ending after the ginon counts its children.
(stand (after it) (SUBJ (kind its)))                                         # After it stands its kind,
(stand then (SUBJ (word mother its)))                                        # then its mother words:
@verse
(and "English" "Deutsch" "Español")
@prose
(be (child its) (SUBJ (and (kind the) (word mother the))))                   # The kind and the mother words are its children.
(count/VERB (OBJ they) (SUBJ (ending its)))                                  # Its ending counts them.
(stand (in (order (of (letter the)))) (SUBJ (root the)))                     # The roots stand in the order of the letters:
@verse
(and "p" "t" "k" "b" "d" "g" "m" "n" "l" "r" "s" "f" "v" "h" "a" "e" "i" "o" "u")
@prose
(be (and old often) (SUBJ (root short the)))                                 # The short roots are old and often said.
(be (and young rare) (SUBJ (root long the)))                                 # The long roots are young or rare.
(have (OBJ (root COUNT)) (SUBJ (book this)))                                 # This book has COUNT roots.
'''

ROUGH_HEADER = '''
## (word rough)
(be rough (SUBJ (word this)))                                               # These words are rough.
(hurt/VERB can (SUBJ they))                                                  # They can hurt.
(use/VERB (OBJ they) rarely)                                                 # Use them rarely.
'''

FIRST_HEADER = '''# Chapter 2b · The first words. Generated by scripts/conlang/roots_book.py --first; do not edit by hand.
## (word first/ADJ the)

(be (word (that (say (SUBJ we)) often most)) (SUBJ (word this)))           # These are the words we say most often.
(learn (OBJ they) first/ADV)                                                 # Learn them first.
(stand first/ADV (in (line every)) (with hyphen) (SUBJ (root a)))           # In every line a root stands first, with a ginon,
(stand then (SUBJ (kind its)))                                               # then its kind,
(stand last/ADV (SUBJ (word mother its)))                                    # last its mother words.
@verse
(kind (of (word the)))                                                       # The kinds of words:
KINDS
@prose

## (relator the)
(link/VERB (OBJ (word other)) (SUBJ (word this)))                           # These words link other words.
(stand (before (word (that (link/VERB (SUBJ they))))) (SUBJ they))           # They stand before the words that they link.
RELATORS

## (word (that (say (SUBJ we)) often most))
FREQUENT

## (word new (of (book this)))
(make/VERB (OBJ (word this)) (for (book this)) (SUBJ we))                   # We made these words for this book.
COINS
'''


def key(root: str) -> tuple:
    return tuple(ORDER[c] for c in root)


def entry(root: str, cls: str, words: list[str]) -> str:
    """The headword is the bare root in mention form (root-ending), so the root never looks like root+vowel:
    `sahen-o veraba count-a zählen-a` is the root sahen with three children (a v3 reviewer read `saheno`
    as a citation form and could not find the root)."""
    kids = [CLASS_WORD.get(cls, "nomun") + "a"] + [f"{w.replace(' ', '_')}-a" for w in words]
    return "@raw " + " ".join([f"{root}-{numeral(len(kids))}"] + kids)


def load(max_rows: int):
    rows = [line.split("\t") for line in (ROOT / "conlang" / "lexicon.tsv").read_text(encoding="utf-8").splitlines()[1:]]
    lex, skipped = [], 0
    for c in rows[:max_rows]:
        root, cl, en, de, es = c[:5]
        if cl == "ROLE":
            lex.append((root, cl, ROLE_WORDS[en]))
            continue
        words = [w for col in (en, de, es) for w in col.split("|")[:1] if w]
        if all(len(w) < 2 or re.fullmatch(r"[ivxlcdm]+", w) for w in words):
            skipped += 1                     # roman numerals and stray letters the treebanks lemmatised as words
            continue
        lex.append((root, cl, words))
    coins = []
    for line in (ROOT / "conlang" / "book" / "coin.tsv").read_text(encoding="utf-8").splitlines()[1:]:
        if line.strip():
            c = (line.split("\t") + [""] * 7)[:7]
            coins.append((c[1], c[2] or "NOUN", [w for w in (c[0], c[4], c[5]) if w], c[6].startswith("field:")))
    return lex, coins, skipped


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--max", type=int, default=6000, help="lexicon rows (heaviest first)")
    p.add_argument("--first", action="store_true", help="write the First Words chapter instead")
    p.add_argument("--top", type=int, default=60, help="--first: how many frequent non-relator words")
    p.add_argument("--out", type=Path, required=True)
    a = p.parse_args()
    lex, coins, skipped = load(a.max)
    if a.first:
        rel = [e for e in lex[:400] if e[1] in RELATOR_CLASSES]
        freq = [e for e in lex if e[1] not in RELATOR_CLASSES][: a.top]
        kinds = "\n".join(f"(={w})" for w in dict.fromkeys(CLASS_WORD[c] for c in
                                                        ("NOUN", "VERB", "ADJ", "ADV", "ADP", "CCONJ", "DET", "PRON",
                                                         "NUM", "PART", "INTJ")))
        text = (FIRST_HEADER.replace("KINDS", kinds)
                .replace("RELATORS", "\n".join(entry(*e) for e in rel))
                .replace("FREQUENT", "\n".join(entry(*e) for e in freq))
                .replace("COINS", "\n".join(entry(*e[:3]) for e in sorted(coins, key=lambda e: key(e[0]))
                                             if not e[3])))   # field words are taught in their field chapters
        a.out.write_text(text, encoding="utf-8")
        print(f"{a.out}: {len(rel)} relators, {len(freq)} frequent words, {sum(not c[3] for c in coins)} coinages")
        return
    entries = {r: (cl, ws) for r, cl, ws in lex}
    for r, cl, ws, is_field in coins:
        if not is_field:                     # field words live in their volume's glossary (conlang/volumes/)
            entries[r] = (cl, ws)
    rough = {r for r, (cl, ws) in entries.items() if ws and ws[0].lower() in ROUGH}
    out = [ROOTS_HEADER.replace("COUNT", str(len(entries)))]
    letter = None
    for root in sorted((r for r in entries if r not in rough), key=key):
        if root[0] != letter:
            letter = root[0]
            out.append(f'\n## ("{letter}")\n')
        out.append(entry(root, *entries[root]))
    out.append(ROUGH_HEADER)
    out.extend(entry(r, *entries[r]) for r in sorted(rough, key=key))
    a.out.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"{a.out}: {len(entries)} entries, {len(rough)} of them fenced as rough ({skipped} junk rows left out)")


if __name__ == "__main__":
    main()
