"""Generate the Book of Roots (conlang/book/08_roots.tl), the dictionary chapter of the founding text.

Every entry is itself a Talema tree: the root heads its mother words, written as literals
(`mito with-a mit-a con-a`: the root mit, with three children, its English, German and Spanish words).
Entries follow Talema's own alphabetical order, p t k b d g m n l r s f v h, then a e i o u, grouped
by first letter. The chapter's opening sentences, which explain all this in Talema, are a template
in this file.

  .venv/bin/python scripts/conlang/roots_book.py --max 6000 --out conlang/book/08_roots.tl
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts" / "conlang"))
from conlang import numeral  # noqa: E402

ORDER = {ch: i for i, ch in enumerate("ptkbdgmnlrsfvhaeiou")}
HEADER = '''# Chapter 8 · The book of roots. Generated by scripts/conlang/roots_book.py; do not edit by hand.
## (book (of root) the)

(be (book (of root) the) (SUBJ this))                                        # This is the book of roots.
(stand first/ADV (in (line every)) (SUBJ (root a)))                          # In every line a root stands first.
(stand (after it) (SUBJ (word mother its)))                                  # After it stand its mother words:
@verse
(and "English" "Deutsch" "Español")
@prose
(be (child its) (SUBJ (word mother the)))                                    # The mother words are its children.
(count/VERB (OBJ they) (SUBJ (ending its)))                                  # Its ending counts them.
(stand (in (order (of (letter the)))) (SUBJ (root the)))                     # The roots stand in the order of the letters:
@verse
(and "p" "t" "k" "b" "d" "g" "m" "n" "l" "r" "s" "f" "v" "h" "a" "e" "i" "o" "u")
@prose
(be (and old often) (SUBJ (root short the)))                                 # The short roots are old and often said.
(be (and young rare) (SUBJ (root long the)))                                 # The long roots are young or rare.
(be (word (for (subject the))) (SUBJ (word SUBJ)))                           # The word pa is the word for the subject.
(be (word (for (object the))) (SUBJ (word OBJ)))                             # The word ta is the word for the object.
(be (word (for (person (that (get (OBJ (thing the))))))) (SUBJ (word DAT)))  # The word papa is for the person who gets the thing.
(have (OBJ (root COUNT)) (SUBJ (book this)))                                 # This book has COUNT roots.
'''


def key(root: str) -> tuple:
    return tuple(ORDER[c] for c in root)


def literal(w: str) -> str:
    return w.replace(" ", "_")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--max", type=int, default=6000, help="entries from the lexicon (heaviest first)")
    p.add_argument("--per-lang", type=int, default=1, help="mother words per language")
    p.add_argument("--out", type=Path, required=True)
    a = p.parse_args()
    entries, skipped = {}, 0
    rows = [l.split("\t") for l in (ROOT / "conlang" / "lexicon.tsv").read_text(encoding="utf-8").splitlines()[1:]]
    for c in rows[: a.max]:
        root, cl, en, de, es = c[:5]
        if cl == "ROLE":
            continue
        words = [w for col in (en, de, es) for w in col.split("|")[: a.per_lang] if w]
        if all(len(w) < 2 or re.fullmatch(r"[ivxlcdm]+", w) for w in words):
            skipped += 1                     # roman numerals and stray letters the treebanks lemmatised as words
            continue
        entries[root] = words
    coin = ROOT / "conlang" / "book" / "coin.tsv"
    for line in coin.read_text(encoding="utf-8").splitlines()[1:]:
        if line.strip():
            c = (line.split("\t") + [""] * 7)[:7]
            entries[c[1]] = [w for w in (c[0], c[4], c[5]) if w]
    out = [HEADER.replace("COUNT", str(len(entries)))]
    letter = None
    for root in sorted(entries, key=key):
        if root[0] != letter:
            letter = root[0]
            out.append(f'\n## ("{letter}")\n')
        ws = entries[root]
        out.append("@raw " + " ".join([root + numeral(len(ws))] + [f"{literal(w)}-a" for w in ws]))
    a.out.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"{a.out}: {len(entries)} entries ({skipped} junk lexicon rows left out)")


if __name__ == "__main__":
    main()
